### ISSUE TITLE
RSS Alternative

### ISSUE THREAD

**Issue by stefansundin** [bethesque/gist-notifications#1]
Hello. I built this: https://gh-rss.herokuapp.com/

Just thought you wanted to know.

**Comment by bethesque** [comment]
Nice work! Much more elegant.

**Comment by bethesque** [comment]
Does it work for private gists?

**Comment by stefansundin** [comment]
No, I wanted to make it as friction-less as possible (no oauthing required, I use my own access token). And since I'm only handling public data now, I don't need to worry about accidentally leaking anything.

But it should be simple to change it to include private data. A secret can be added to the url, e.g. `bethesque.xml?private_key=abc123`, which decrypts to your personal access token that can read your private gists. But then the url has to be kept secret as well.

**Comment by bethesque** [comment]
Yup, makes sense. You don't really want your private key turning up in HTTP logs across the world. Thanks for the work!
